// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCollectionFolder(arg1, arg2) {
  return window['go']['app']['App']['AddCollectionFolder'](arg1, arg2);
}

export function AddEnv() {
  return window['go']['app']['App']['AddEnv']();
}

export function AddRequestToCollection(arg1, arg2) {
  return window['go']['app']['App']['AddRequestToCollection'](arg1, arg2);
}

export function AddVariable(arg1, arg2) {
  return window['go']['app']['App']['AddVariable'](arg1, arg2);
}

export function ClientLsTabs() {
  return window['go']['app']['App']['ClientLsTabs']();
}

export function CloseTab(arg1) {
  return window['go']['app']['App']['CloseTab'](arg1);
}

export function CloseTabMul(arg1) {
  return window['go']['app']['App']['CloseTabMul'](arg1);
}

export function CopyRequest(arg1) {
  return window['go']['app']['App']['CopyRequest'](arg1);
}

export function CreateBlankRequest() {
  return window['go']['app']['App']['CreateBlankRequest']();
}

export function CreateNewTab() {
  return window['go']['app']['App']['CreateNewTab']();
}

export function CreateOrUseExistTab(arg1, arg2, arg3) {
  return window['go']['app']['App']['CreateOrUseExistTab'](arg1, arg2, arg3);
}

export function DelEnv(arg1) {
  return window['go']['app']['App']['DelEnv'](arg1);
}

export function DelFileLikeRecord(arg1) {
  return window['go']['app']['App']['DelFileLikeRecord'](arg1);
}

export function DelVars(arg1) {
  return window['go']['app']['App']['DelVars'](arg1);
}

export function DuplicateTab(arg1) {
  return window['go']['app']['App']['DuplicateTab'](arg1);
}

export function GetBaseUrl() {
  return window['go']['app']['App']['GetBaseUrl']();
}

export function GetFilePathPlaceholder() {
  return window['go']['app']['App']['GetFilePathPlaceholder']();
}

export function GetFileUrl() {
  return window['go']['app']['App']['GetFileUrl']();
}

export function GetFolderIdByReqId(arg1) {
  return window['go']['app']['App']['GetFolderIdByReqId'](arg1);
}

export function GetPort() {
  return window['go']['app']['App']['GetPort']();
}

export function GetRequestById(arg1) {
  return window['go']['app']['App']['GetRequestById'](arg1);
}

export function GetVarsByEnvId(arg1) {
  return window['go']['app']['App']['GetVarsByEnvId'](arg1);
}

export function LsAllEnv() {
  return window['go']['app']['App']['LsAllEnv']();
}

export function LsCollectionFolder(arg1) {
  return window['go']['app']['App']['LsCollectionFolder'](arg1);
}

export function LsRequestOfCollection(arg1) {
  return window['go']['app']['App']['LsRequestOfCollection'](arg1);
}

export function ModifyVariable(arg1, arg2) {
  return window['go']['app']['App']['ModifyVariable'](arg1, arg2);
}

export function NativeFileDialog(arg1, arg2) {
  return window['go']['app']['App']['NativeFileDialog'](arg1, arg2);
}

export function NativeMessageDialog(arg1) {
  return window['go']['app']['App']['NativeMessageDialog'](arg1);
}

export function RemoveCollection(arg1) {
  return window['go']['app']['App']['RemoveCollection'](arg1);
}

export function RenameEnv(arg1, arg2) {
  return window['go']['app']['App']['RenameEnv'](arg1, arg2);
}

export function RenameFileLikeRequest(arg1, arg2) {
  return window['go']['app']['App']['RenameFileLikeRequest'](arg1, arg2);
}

export function RenameFolder(arg1, arg2) {
  return window['go']['app']['App']['RenameFolder'](arg1, arg2);
}

export function RenameTab(arg1, arg2) {
  return window['go']['app']['App']['RenameTab'](arg1, arg2);
}

export function SetCurrent(arg1) {
  return window['go']['app']['App']['SetCurrent'](arg1);
}

export function UpdateRequestInfo(arg1) {
  return window['go']['app']['App']['UpdateRequestInfo'](arg1);
}
