// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {folder} from '../models';
import {env} from '../models';
import {filelike} from '../models';
import {tab} from '../models';
import {request} from '../models';
import {frontend} from '../models';
import {app} from '../models';

export function AddCollectionFolder(arg1:string,arg2:number):Promise<folder.Folder>;

export function AddEnv():Promise<env.Env>;

export function AddRequestToCollection(arg1:number,arg2:string):Promise<filelike.FileLike>;

export function AddVariable(arg1:number,arg2:string):Promise<void>;

export function ClientLsTabs():Promise<Array<tab.Tab>>;

export function CloseTab(arg1:number):Promise<void>;

export function CloseTabMul(arg1:Array<number>):Promise<void>;

export function CopyRequest(arg1:number):Promise<request.RequestRecord>;

export function CreateBlankRequest():Promise<request.RequestRecord>;

export function CreateNewTab():Promise<tab.Tab>;

export function CreateOrUseExistTab(arg1:number,arg2:string,arg3:string):Promise<number>;

export function DelEnv(arg1:number):Promise<void>;

export function DelFileLikeRecord(arg1:number):Promise<void>;

export function DelVars(arg1:number):Promise<void>;

export function DuplicateTab(arg1:number):Promise<Array<tab.Tab>>;

export function GetBaseUrl():Promise<string>;

export function GetFilePathPlaceholder():Promise<string>;

export function GetFileUrl():Promise<string>;

export function GetFolderIdByReqId(arg1:number):Promise<number>;

export function GetPort():Promise<number>;

export function GetRequestById(arg1:number):Promise<request.RequestRecord>;

export function GetVarsByEnvId(arg1:number):Promise<Array<env.Vars>>;

export function LsAllEnv():Promise<Array<env.Env>>;

export function LsCollectionFolder(arg1:number):Promise<Array<folder.Folder>>;

export function LsRequestOfCollection(arg1:number):Promise<Array<filelike.FileLike>>;

export function ModifyVariable(arg1:number,arg2:env.Vars):Promise<void>;

export function NativeFileDialog(arg1:frontend.OpenDialogOptions,arg2:boolean):Promise<app.FileInfo>;

export function NativeMessageDialog(arg1:frontend.MessageDialogOptions):Promise<string>;

export function RemoveCollection(arg1:number):Promise<void>;

export function RenameEnv(arg1:number,arg2:string):Promise<void>;

export function RenameFileLikeRequest(arg1:string,arg2:number):Promise<void>;

export function RenameFolder(arg1:string,arg2:number):Promise<void>;

export function RenameTab(arg1:string,arg2:number):Promise<void>;

export function SetCurrent(arg1:number):Promise<void>;

export function UpdateRequestInfo(arg1:request.RequestRecord):Promise<void>;
