// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPort() {
  return window['go']['app']['App']['GetPort']();
}

export function NativeFileDialog(arg1, arg2) {
  return window['go']['app']['App']['NativeFileDialog'](arg1, arg2);
}

export function NativeMessageDialog(arg1) {
  return window['go']['app']['App']['NativeMessageDialog'](arg1);
}

export function SimpleRequest(arg1) {
  return window['go']['app']['App']['SimpleRequest'](arg1);
}
