// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {frontend} from '../models';

export function AddRequest(arg1:model.AppRequest):Promise<any>;

export function CloseTab(arg1:number):Promise<void>;

export function GetPort():Promise<number>;

export function GetRecordById(arg1:number):Promise<{[key: string]: any}>;

export function LsAllTabs():Promise<Array<{[key: string]: any}>>;

export function NativeFileDialog(arg1:frontend.OpenDialogOptions,arg2:boolean):Promise<model.FileInfo>;

export function NativeMessageDialog(arg1:frontend.MessageDialogOptions):Promise<string>;

export function SimpleRequest(arg1:model.AppRequest):Promise<any>;

export function StartNewTab():Promise<number>;

export function UpdateTabInfo(arg1:model.TabPage):Promise<string>;
