// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRequest(arg1) {
  return window['go']['app']['App']['AddRequest'](arg1);
}

export function CloseTab(arg1) {
  return window['go']['app']['App']['CloseTab'](arg1);
}

export function GetPort() {
  return window['go']['app']['App']['GetPort']();
}

export function GetRecordById(arg1) {
  return window['go']['app']['App']['GetRecordById'](arg1);
}

export function LsAllTabs() {
  return window['go']['app']['App']['LsAllTabs']();
}

export function NativeFileDialog(arg1, arg2) {
  return window['go']['app']['App']['NativeFileDialog'](arg1, arg2);
}

export function NativeMessageDialog(arg1) {
  return window['go']['app']['App']['NativeMessageDialog'](arg1);
}

export function SimpleRequest(arg1) {
  return window['go']['app']['App']['SimpleRequest'](arg1);
}

export function StartNewTab() {
  return window['go']['app']['App']['StartNewTab']();
}

export function UpdateTabInfo(arg1) {
  return window['go']['app']['App']['UpdateTabInfo'](arg1);
}
