export enum ContentType {
  Json = "application/json",
  FormUrl = "application/x-www-form-urlencoded",
  Text = "text/plain",
  SopaAndXml = "application/soap+xml",
  ApplicaitonXml = "application/xml",
  TextXml = "text/xml",
  XmlCommonSign = 'xml',
  Html = "text/html",
  Image = "image/",
  Audio = "audio/",
  Video = "video/",
  Pdf = "pdf",
  MultipartFormData = "multipart/form-data",
  File = "application/octet-stream",
}
